FROM python:3.8

ARG ENVIRONMENT


WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install -r /code/requirements.txt

ENV ENVIRONMENT=$ENVIRONMENT
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./app /code/app
COPY ./alembic.ini /code/alembic.ini
COPY ./alembic /code/alembic
COPY ./scripts /code/scripts
COPY ./.env.local /code/.env.local
