"""initial_schema

Revision ID: 981cb71893e2
Revises: 
Create Date: 2022-04-04 21:57:19.725334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "981cb71893e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camera",
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "time_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "review",
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "time_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("camera_uuid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_uuid"], ["camera.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    op.drop_table("camera")
    # ### end Alembic commands ###
